# Generated by Django 4.1.7 on 2023-03-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('Designation', models.CharField(max_length=60)),
                ('Account', models.CharField(max_length=60)),
                ('Employee_Number', models.IntegerField()),
                ('Date_of_joining', models.DateTimeField()),
            ],
        ),
    ]
